// Local text-generation provider for summaries (P3-T2, OPEN-8 resolution).
//
// User decision: summaries are generated by a local model on this machine —
// no API, no key management, data stays local. This module is that choice,
// implemented with `@huggingface/transformers` (transformers.js), the same
// library the plan already named for the *embeddings* side of R67.
//
// **The honest trade-offs, stated in the code so they are not rediscovered:**
// a local CPU instruct model is slower per call and more prone to the exact
// hallucination R62/R63 forbid ("describe only the facts shown"). R64 makes
// that a one-time cost — summaries are cached by `input_sha256`, so generation
// runs once per stable input, not per query. A model that is good enough for
// "three sentences about a function whose signature, callees and exits are in
// the prompt" is good enough for this project.
//
// The first actual generation downloads the model ONNX weights (~hundreds of
// MB) and can take minutes on CPU. That is not a bug; it is the local-model
// trade. Subsequent runs reuse the weight cache.
//
// Token counts: LOCAL generation has no per-token monetary cost, so the R64
// counting columns stay NULL rather than pretending locally-generated text
// carries the same cost shape as an API. Cost here is elapsed time, and the
// CLI prints it.

import { pipeline, type Message } from "@huggingface/transformers";
import type { SummaryProvider } from "./summaries.ts";

export const LOCAL_DEFAULT_MODEL = "onnx-community/Qwen2.5-0.5B-Instruct";

export type LocalDtype = "auto" | "fp32" | "fp16" | "q8" | "int8" | "uint8" | "q4" | "q2";

export interface LocalSummaryOptions {
  model?: string;
  device?: "cpu" | "auto" | "wasm" | "dml" | "cuda" | "webgpu";
  /** Passed to the pipeline only when set; the model registry picks otherwise. */
  dtype?: LocalDtype;
  maxNewTokens?: number;
  temperature?: number;
  topP?: number;
}

interface GenerateResult {
  text: string;
  tokensIn: number | null;
  tokensOut: number | null;
}

type GenerateFn = (
  prompt: string, maxNewTokens: number, temperature: number, topP: number,
) => Promise<GenerateResult>;

// The library's `TextGenerationPipeline.call` generic over
// `string | Chat | string[] | Chat[]` makes the chat-array call path resolve
// to a wide union instead of the single concrete shape we invoke. This seam
// keeps the runtime contract explicit (chat in, chat output out) without
// importing the library's intricate generics into this module.
type TextGenHook = {
  call(
    texts: Message[], options: Record<string, number | string>,
  ): Promise<Array<{ generated_text?: unknown }>>;
};

/** The one end-user escape hatch for model choice, before config plumbing exists. */
export function modelFromEnv(): { model: string; device?: LocalSummaryOptions["device"] } {
  const model = process.env["CODE_INTEL_LLM_MODEL"];
  const device = (process.env["CODE_INTEL_LLM_DEVICE"] ?? "") as LocalSummaryOptions["device"];
  return { model: model && model.length > 0 ? model : LOCAL_DEFAULT_MODEL, device: device || undefined };
}

export class LocalSummaryProvider implements SummaryProvider {
  readonly name = "local:transformers";
  readonly model: string;
  private readonly generate: GenerateFn;
  private readonly maxNewTokens: number;
  private readonly temperature: number;
  private readonly topP: number;

  private constructor(
    model: string, generate: GenerateFn, maxNewTokens: number, temperature: number, topP: number,
  ) {
    this.model = model;
    this.generate = generate;
    this.maxNewTokens = maxNewTokens;
    this.temperature = temperature;
    this.topP = topP;
  }

  /**
   * Load the model once per process and return a ready provider.
   *
   * Loading is deliberately a separate step: nothing in the core module
   * (`summaries.ts`) can reach this code, and the CLI only calls it when a
   * cache miss actually needs generating — never for reads or caching test
   * runs. Failures here (no weights, wrong dtype, OOM) surface as a loud
   * error with a remedy, not as "no summary".
   */
  static async load(options: LocalSummaryOptions = {}): Promise<LocalSummaryProvider> {
    const model = options.model ?? LOCAL_DEFAULT_MODEL;
    const device = options.device ?? "cpu";
    const pipe = await pipeline("text-generation", model, {
      device,
      ...(options.dtype ? { dtype: options.dtype } : {}),
    }) as unknown as TextGenHook;

    const generate: GenerateFn = async (prompt, maxNewTokens, temperature, topP) => {
      // Instruct models (Qwen2.5-Instruct) expect chat-message input; a bare
      // string would skip the template and leak chat tokens into output.
      const output = await pipe.call(
        [{ role: "user", content: prompt }],
        { max_new_tokens: maxNewTokens, temperature, top_p: topP },
      );
      const chat = output[0]?.generated_text;
      const last = Array.isArray(chat) ? chat.at(-1) : undefined;
      const message = last as { content?: unknown } | undefined;
      const text = typeof message?.content === "string" ? message.content : "";
      return { text, tokensIn: null, tokensOut: null };
    };

    return new LocalSummaryProvider(model, generate, options.maxNewTokens ?? 96, options.temperature ?? 0.2, options.topP ?? 0.9);
  }

  async complete(prompt: string): Promise<{ text: string; tokensIn?: number; tokensOut?: number }> {
    const result = await this.generate(prompt, this.maxNewTokens, this.temperature, this.topP);
    return { text: result.text, tokensIn: result.tokensIn ?? undefined, tokensOut: result.tokensOut ?? undefined };
  }
}

// ---------------------------------------------------------------------------
// lazy singleton — one model load per process, only on first real generation
// ---------------------------------------------------------------------------

let cached: Promise<LocalSummaryProvider> | null = null;

export function localSummaryProvider(): Promise<LocalSummaryProvider> {
  if (!cached) cached = LocalSummaryProvider.load(modelFromEnv());
  return cached;
}